
@startuml

class Temporizador{

}

interface Temporizavel{

+ timeOut() : void
}
class Porta{

}

class PortaComAlarme{

}

Temporizador --> Temporizavel
PortaComAlarme --|> Porta
PortaComAlarme ..|> Temporizavel
@enduml